# Generated by Django 2.1.3 on 2019-12-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='pid',
            field=models.CharField(default='P', max_length=100),
        ),
        migrations.AlterField(
            model_name='park',
            name='uid',
            field=models.IntegerField(default=None),
        ),
    ]
