# Generated by Django 2.2.4 on 2019-12-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rp', models.IntegerField()),
                ('uid', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('enters', models.TimeField(auto_now_add=True)),
                ('exits', models.TimeField(auto_now=True)),
            ],
        ),
    ]
