# Generated by Django 2.2.4 on 2019-12-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dist',
            name='exits',
            field=models.TimeField(),
        ),
    ]
