# Generated by Django 2.2.4 on 2019-12-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distro', '0002_auto_20191207_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dist',
            name='enters',
            field=models.TimeField(),
        ),
    ]
