# Generated by Django 2.2.4 on 2019-12-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distro', '0003_auto_20191207_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dist',
            name='enters',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='dist',
            name='exits',
            field=models.DateTimeField(),
        ),
    ]
