# Generated by Django 2.1.3 on 2019-12-19 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distro', '0005_auto_20191217_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rp', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=300)),
            ],
        ),
    ]
